# Generated by Django 4.0.6 on 2022-10-22 14:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('mrp', models.FloatField()),
                ('img1', models.ImageField(upload_to='product_img')),
                ('img2', models.ImageField(upload_to='product_img')),
                ('img3', models.ImageField(upload_to='product_img')),
                ('img4', models.ImageField(upload_to='product_img')),
                ('product_details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('trending', models.BooleanField(default=False)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='manikshop.category')),
                ('subcategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='manikshop.subcategory')),
            ],
        ),
    ]
