# Generated by Django 4.0.6 on 2022-10-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manikshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sub_cat',
            field=models.ManyToManyField(blank=True, related_name='sub_cat', to='manikshop.subcategory'),
        ),
    ]
