# Generated by Django 4.0.6 on 2022-10-22 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manikshop', '0003_remove_category_sub_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetails',
            old_name='img4',
            new_name='main_img',
        ),
    ]
