# Generated by Django 4.0.6 on 2022-10-23 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manikshop', '0004_rename_img4_productdetails_main_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='category',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='manikshop.category'),
        ),
    ]
