# Generated by Django 4.0.6 on 2022-10-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manikshop', '0010_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutomer_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('address', models.CharField(max_length=500)),
                ('mobile_no', models.CharField(max_length=12)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('confirm', 'Confirm'), ('on_the_way', 'On the way'), ('delivered', 'Delivered')], default='pending', max_length=50)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('confirm', 'Confirm')], default='pending', max_length=50)),
                ('order_list', models.ManyToManyField(related_name='order_list', to='manikshop.productdetails')),
            ],
        ),
    ]
