# Generated by Django 4.0.6 on 2022-10-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manikshop', '0012_order_order_id_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
