# Generated by Django 4.0.6 on 2022-10-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manikshop', '0014_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cust_name',
            new_name='name',
        ),
    ]
