# Generated by Django 4.0.6 on 2022-10-27 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manikshop', '0015_rename_cust_name_cart_name'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='manikshop.productdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.FloatField(default=1),
        ),
        
    ]
