# Generated by Django 4.1.4 on 2023-01-27 17:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manikshop', '0018_remove_order_order_list_order_update_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('subject', models.CharField(max_length=500)),
                ('mobile_no', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 1, 27, 23, 21, 16, 197628))),
            ],
        ),
    ]
