# Generated by Django 4.1.4 on 2023-02-01 20:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manikshop', '0019_contact_form_remove_order_order_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_order_id',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact_form',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 1, 34, 6, 667061)),
        ),
    ]
