# Generated by Django 4.1.4 on 2023-02-02 09:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manikshop', '0020_remove_order_order_list_order_payment_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extended_user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
